### ISSUE TITLE
Prepojiť html stránky pomocou Flask

### ISSUE THREAD

**Issue by saraguzi** [TIS2023-FMFI/kontrola-dorucenia#23]

**Comment by saraguzi** [comment]
V novej vetve projekt je kód, ktorý prepája html stránky, obsahuje sqlite databázu s jedným používateľom, ktorý sa vie prihlásiť

Prosím skontrolujte a otestujte, či to funguje

Vytvorila som aj pull request

**Comment by Veron32** [comment]
Prihlasovanie funguje

**Comment by Veron32** [comment]
Pracujem na funkcionalite: prihlásenie, odhlásenie, vypísanie informácií o používateľovi, zmena hesla.
