### ISSUE TITLE
Návrh stránok aplikácie pomocou Moqups

### ISSUE THREAD

**Issue by saraguzi** [TIS2023-FMFI/kontrola-dorucenia#8]

**Comment by saraguzi** [comment]
Odkaz: https://app.moqups.com/cqhOMM09B1PrpTeuXdzQGxViHsn12J20/view/page/a0cec6555

**Comment by saraguzi** [comment]
Upravila som stránky 1-4 na základe stretnutia so zadávateľom a doplnila odhlasovanie :)

**Comment by Veron32** [comment]
Upravila som stránku na strane dispečera dopravcu + vytvorila som ďalšiu v angličtine. Prosím, skontrolujte, či to spĺňa požiadavky z posledného stretnutia so zadávateľom. Prípadne píšte dotazy.

**Comment by saraguzi** [comment]
Pridala som do Návrhu texty ku stránkam na strane CEVA dispečerov

Veronika, myslím, že je to dobre upravené, môžeme pridať ešte prepínanie jazyka

**Comment by Veron32** [comment]
Pridala som prepínanie jazyka
